services:
  - type: web
    name: sonicflow
    runtime: node
    plan: free
    nodeVersion: 20
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
